# 抓取设置
fetch_settings:
  # 抓取模式: 'keyword' (关键词模式) 或 'category' (分类模式)
  method: 'category'
  # 在分类模式下，获取过去多少天的论文 (1 = 只获取今天)
  category_fetch_days_ago: 2
  # 在分类模式下，每个来源最多获取的论文总数
  max_papers_per_category_fetch: 10
  # 在分类模式下，是否确保每个子分类都抓取到论文
  ensure_diversity_in_category_fetch: true
  # 在分类模式下，每个子分类最少抓取的论文数
  min_papers_per_sub_category: 1
  # 在分类模式下，每个子分类最多抓取的论文数
  max_papers_per_sub_category: 3
  # 在关键词模式下，从bioRxiv获取过去多少天的论文
  biorxiv_days_ago: 3
  # 在关键词模式下，从arXiv获取的最大论文数量
  arxiv_max_results_kw: 100

# bioRxiv/medRxiv Markdown 输出配置
output_settings:
  # 是否在生成的 .md 文件中包含论文摘要
  biorxiv_include_abstract_in_md: true

# 关键词列表 (仅在 keyword 模式下生效)
keywords:
  - "translational medicine"
  - "systems biology"
  - "synthetic biology"
  - "genomics"
  - "bioinformatics"
  - "medical artificial intelligence"
  - "medical ai"

# 分类列表 (仅在 category 模式下生效)
categories:
  arxiv:
    - 'cs.CV'    # 计算机视觉
    - 'q-bio.GN' # 基因组学
    - 'q-bio.MN' # 分子网络
    - 'q-bio.CB' # 细胞行为
    - 'q-bio.BM' # 生物分子
    - 'q-bio.QM'  # 定量方法
  biorxiv:
    - 'bioengineering'
    - 'bioinformatics'
    - 'genomics'
    - 'synthetic biology'
    - 'systems biology'
    - 'molecular biology'
    - 'cancer biology'
