categories:
  arxiv:
  - cs.CV
  - q-bio.GN
  - q-bio.MN
  - q-bio.CB
  - q-bio.BM
  - q-bio.QM
  biorxiv:
  - bioengineering
  - bioinformatics
  - genomics
  - synthetic biology
  - systems biology
  - molecular biology
  - cancer biology
  chinese_arxiv: []
  chinese_biorxiv: []
fetch_settings:
  method: category
  arxiv_max_results_kw: 100
  max_papers_per_category_fetch: 10
  search_by_authors: []
  search_by_ids: []
  arxiv_sort_by: SubmittedDate
  arxiv_sort_order: Descending
  keyword_search_field: all
  search_start_date: ''
  search_end_date: ''
keywords:
- translational medicine
- systems biology
- synthetic biology
- genomics
- bioinformatics
- medical artificial intelligence
- medical ai
output_settings:
  biorxiv_include_abstract_in_md: true
